package protoschema

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// GenerateSwift emits Swift `Codable` structs for every type in the protocol
// schema's $defs, derived from the same buildDoc() walk as the JSON schema. The
// output is a single self-contained file that depends only on the hand-written
// JSONValue support type (Sources/VixProtocol/JSONValue.swift) and Foundation.
//
// The Go structs → schema → Swift chain is fully mechanical: a committed-file
// drift test on both outputs keeps the Swift models in lockstep with the daemon.
func GenerateSwift() ([]byte, error) {
	doc := buildDoc()
	defs, ok := doc["$defs"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("buildDoc: missing $defs")
	}

	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/protoschema (-lang swift). DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `make mac-models` after changing internal/protocol.\n")
	b.WriteString("//\n")
	b.WriteString("// These types mirror the vix daemon\u21c4client wire protocol\n")
	b.WriteString("// (internal/protocol). They decode the `data` payload of a ThreadEvent\n")
	b.WriteString("// and encode the `data` of a ThreadCommand.\n\n")
	b.WriteString("import Foundation\n")

	for _, name := range names {
		node, _ := defs[name].(map[string]any)
		if node == nil {
			continue
		}
		emitStruct(&b, name, node)
	}

	return b.Bytes(), nil
}

// emitStruct writes one `public struct` for an object $def.
func emitStruct(b *bytes.Buffer, name string, node map[string]any) {
	props, _ := node["properties"].(map[string]any)
	required := requiredSet(node)

	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	type field struct {
		prop     string // Swift property identifier (escaped if needed)
		jsonKey  string
		swiftTyp string
		optional bool
	}
	fields := make([]field, 0, len(keys))
	for _, jsonKey := range keys {
		fn, _ := props[jsonKey].(map[string]any)
		t := swiftType(fn)
		opt := !required[jsonKey]
		fields = append(fields, field{
			prop:     swiftIdent(camelCase(jsonKey)),
			jsonKey:  jsonKey,
			swiftTyp: t,
			optional: opt,
		})
	}

	fmt.Fprintf(b, "\npublic struct %s: Codable, Sendable, Equatable {\n", name)

	// Stored properties.
	for _, f := range fields {
		typ := f.swiftTyp
		if f.optional {
			typ += "?"
		}
		fmt.Fprintf(b, "    public var %s: %s\n", f.prop, typ)
	}

	// Public memberwise initializer (synthesized inits are internal, so an
	// external module — vix-mac-probe — could not construct commands without
	// this).
	b.WriteString("\n    public init(")
	params := make([]string, 0, len(fields))
	for _, f := range fields {
		typ := f.swiftTyp
		if f.optional {
			params = append(params, fmt.Sprintf("%s: %s? = nil", f.prop, typ))
		} else {
			params = append(params, fmt.Sprintf("%s: %s", f.prop, typ))
		}
	}
	b.WriteString(strings.Join(params, ", "))
	b.WriteString(") {\n")
	for _, f := range fields {
		fmt.Fprintf(b, "        self.%s = %s\n", f.prop, f.prop)
	}
	b.WriteString("    }\n")

	// Explicit CodingKeys map camelCase properties to their JSON keys.
	if len(fields) > 0 {
		b.WriteString("\n    enum CodingKeys: String, CodingKey {\n")
		for _, f := range fields {
			fmt.Fprintf(b, "        case %s = %q\n", f.prop, f.jsonKey)
		}
		b.WriteString("    }\n")
	}

	b.WriteString("}\n")
}

// requiredSet returns the set of JSON keys marked required in an object schema.
func requiredSet(node map[string]any) map[string]bool {
	out := map[string]bool{}
	switch req := node["required"].(type) {
	case []string:
		for _, r := range req {
			out[r] = true
		}
	case []any:
		for _, r := range req {
			if s, ok := r.(string); ok {
				out[s] = true
			}
		}
	}
	return out
}

// swiftType maps a schema node to a Swift type name.
func swiftType(node map[string]any) string {
	if ref, ok := node["$ref"].(string); ok {
		return strings.TrimPrefix(ref, "#/$defs/")
	}
	switch typ, _ := node["type"].(string); typ {
	case "string":
		return "String"
	case "boolean":
		return "Bool"
	case "integer":
		return "Int64"
	case "number":
		return "Double"
	case "array":
		items, _ := node["items"].(map[string]any)
		return "[" + swiftType(items) + "]"
	case "object":
		if ap, ok := node["additionalProperties"].(map[string]any); ok {
			return "[String: " + swiftType(ap) + "]"
		}
		return "[String: JSONValue]"
	default:
		// No type constraint: any / json.RawMessage.
		return "JSONValue"
	}
}

// camelCase converts a snake_case JSON key to lowerCamelCase.
func camelCase(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for i, p := range parts {
		if p == "" {
			continue
		}
		if i == 0 {
			b.WriteString(p)
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	if b.Len() == 0 {
		return s
	}
	return b.String()
}

// swiftKeywords are reserved words that must be backtick-escaped when used as
// identifiers.
var swiftKeywords = map[string]bool{
	"associatedtype": true, "class": true, "deinit": true, "enum": true,
	"extension": true, "fileprivate": true, "func": true, "import": true,
	"init": true, "inout": true, "internal": true, "let": true, "open": true,
	"operator": true, "private": true, "protocol": true, "public": true,
	"rethrows": true, "static": true, "struct": true, "subscript": true,
	"typealias": true, "var": true, "break": true, "case": true,
	"continue": true, "default": true, "defer": true, "do": true, "else": true,
	"fallthrough": true, "for": true, "guard": true, "if": true, "in": true,
	"repeat": true, "return": true, "switch": true, "where": true,
	"while": true, "as": true, "catch": true, "false": true, "is": true,
	"nil": true, "self": true, "super": true, "throw": true, "throws": true,
	"true": true, "try": true,
}

// swiftIdent backtick-escapes an identifier when it collides with a keyword.
func swiftIdent(name string) string {
	if swiftKeywords[name] {
		return "`" + name + "`"
	}
	return name
}
