package scenarios

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/get-vix/vix/e2e/harness"
)

// This scenario drives the GitHub-plan job's tracker bookkeeping end to end
// through the real workflow engine (placeholder substitution of $(step.fetch)
// / $(step.select) / $(workflow.dir), the NO_TODO edge gate, and the per-run
// job runner), firing it repeatedly via `vix job run`. It pins the two
// robustness fixes to the select/mark_done contract generated by the mission
// control builder (internal/daemon/web/source/src/data/jobWorkflows.ts):
//
//   Fix 1 — a FAILED fetch (FETCH_FAILED sentinel) must leave the tracker
//     completely untouched, so a transient network/API blip can never wipe
//     every item's state and re-trigger a full re-investigation on the next
//     good fetch.
//   Fix 2 — an item left "doing" by a run that was hard-cancelled/timed-out
//     before mark_done is re-armed to "todo" for another attempt, bounded to
//     2 attempts before it is abandoned ("done") so a perpetually-timing-out
//     item can't loop forever.
//
// The steps below carry the SAME fetch/select/mark_done bash as the builder
// (fetch is stubbed to a test-controlled feed file, and the agent/detail steps
// are omitted, so the run is deterministic and needs no LLM). The full
// gh/API/none access-branch graph remains the (skipped) acceptance spec in
// jobs_github_plan_test.go — this focuses on the tracker state machine the
// fixes changed, which is workflow-shape-agnostic.

const trackerJobID = "e2e-tracker"

// fetchBashE2E stands in for the builder's fetch step: it fails to a
// FETCH_FAILED sentinel when a `fetch_fail` marker exists (simulating a
// network/API error), otherwise emits the deduped open URLs from feed.txt.
const fetchBashE2E = `if [ -f fetch_fail ]; then echo FETCH_FAILED; exit 0; fi
grep -oE 'https://github\.com/[^"]+/(issues|pull)/[0-9]+' feed.txt 2>/dev/null | sort -u`

// selectBashE2E is the builder's select step verbatim (the emitted form).
const selectBashE2E = `tracker="$(workflow.dir)/tracker.tsv"
tmp="$tracker.tmp"
case "$(step.fetch)" in *FETCH_FAILED*) echo NO_TODO; exit 0;; esac
open=$(printf '%s\n' "$(step.fetch)")
: > "$tmp"
if [ -f "$tracker" ]; then
  while IFS=$'\t' read -r st att url; do
    [ -n "$url" ] || { url=$att; att=0; }
    [ -n "$url" ] || continue
    case $att in ''|*[!0-9]*) att=0;; esac
    if printf '%s\n' "$open" | grep -qxF "$url"; then
      printf '%s\t%s\t%s\n' "$st" "$att" "$url" >> "$tmp"
    fi
  done < "$tracker"
fi
printf '%s\n' "$open" | while IFS= read -r url; do
  [ -n "$url" ] || continue
  if ! cut -f3 "$tmp" | grep -qxF "$url"; then
    printf 'todo\t0\t%s\n' "$url" >> "$tmp"
  fi
done
mv "$tmp" "$tracker"
while IFS=$'\t' read -r st att url; do
  if [ "$st" = doing ]; then
    if [ "$att" -ge 2 ]; then st=done; else st=todo; fi
  fi
  printf '%s\t%s\t%s\n' "$st" "$att" "$url"
done < "$tracker" > "$tmp" && mv "$tmp" "$tracker"
sel=$(while IFS=$'\t' read -r st att url; do [ "$st" = todo ] && { printf '%s' "$url"; break; }; done < "$tracker")
if [ -z "$sel" ]; then echo NO_TODO; exit 0; fi
while IFS=$'\t' read -r st att url; do
  if [ "$url" = "$sel" ]; then att=$((att + 1)); printf 'doing\t%s\t%s\n' "$att" "$url"; else printf '%s\t%s\t%s\n' "$st" "$att" "$url"; fi
done < "$tracker" > "$tmp" && mv "$tmp" "$tracker"
echo "$sel"`

// doneBashE2E is the builder's mark_done step verbatim, prefixed with a test
// gate: a `skip_done` marker simulates a run that died before mark_done ran
// (a hard timeout/cancel), leaving the claimed item stuck in "doing".
const doneBashE2E = `if [ -f skip_done ]; then exit 0; fi
tracker="$(workflow.dir)/tracker.tsv"
url=$(printf '%s' "$(step.select)")
[ -f "$tracker" ] || exit 0
[ -n "$url" ] || exit 0
tmp="$tracker.tmp"
while IFS=$'\t' read -r st att u; do
  [ -n "$u" ] || { u=$att; att=0; }
  [ -n "$u" ] || continue
  case $att in ''|*[!0-9]*) att=0;; esac
  if [ "$u" = "$url" ]; then printf 'done\t%s\t%s\n' "$att" "$u"; else printf '%s\t%s\t%s\n' "$st" "$att" "$u"; fi
done < "$tracker" > "$tmp" && mv "$tmp" "$tracker"`

func trackerJobSpec() string {
	spec := map[string]any{
		"id":          trackerJobID,
		"name":        "Tracker e2e",
		"enabled":     true,
		"trigger":     map[string]any{"type": "at", "time": "2099-01-01T00:00:00Z"},
		"prompt":      "tracker bookkeeping e2e",
		"cwd":         "{{WORKDIR}}",
		"created_by":  "web",
		"permissions": map[string]any{"auto_write": true, "auto_dirs": true},
		"workflow": map[string]any{
			"name":        "e2e-tracker-wf",
			"entry_point": map[string]any{"id": "fetch"},
			"steps": map[string]any{
				"fetch": map[string]any{
					"type":       "bash",
					"command":    fetchBashE2E,
					"next_steps": []any{map[string]any{"id": "select"}},
				},
				"select": map[string]any{
					"type":    "bash",
					"command": selectBashE2E,
					"next_steps": []any{map[string]any{
						"id":         "done",
						"execute_if": `[[ "$(step.select)" != *NO_TODO* ]]`,
					}},
				},
				"done": map[string]any{"type": "bash", "command": doneBashE2E},
			},
		},
	}
	b, _ := json.Marshal(spec)
	return string(b)
}

// countJobRuns counts completed (job_status set) Vix-initiated sessions for a
// job id, used to gate one `vix job run` on completion before firing the next.
func countJobRuns(h *harness.Harness, ref string) int {
	dir := h.HomePath(".vix/sessions/open")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0
	}
	n := 0
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var r planRunRecord
		if json.Unmarshal(b, &r) != nil {
			continue
		}
		if r.Origin == "vix" && r.Trigger.Ref == ref && r.JobStatus != "" {
			n++
		}
	}
	return n
}

// TestJobGithubTrackerBookkeeping fires the tracker job repeatedly and asserts
// tracker.tsv after each run: a failed fetch preserves it, and a stuck "doing"
// item is retried once then abandoned (bounded to 2 attempts).
func TestJobGithubTrackerBookkeeping(t *testing.T) {
	const a = "https://github.com/o/r/issues/1"
	const b = "https://github.com/o/r/issues/2"

	h := harness.Start(t, harness.Meta{
		Category:    "jobs",
		Subcategory: "jobs.github_tracker",
		Description: "the GitHub-plan tracker preserves state on a failed fetch and re-arms a stuck 'doing' item, bounded to 2 attempts before abandoning it",
		Wire:        harness.WireMessages,
	},
		harness.WithEnv("VIX_DISABLE_JOBS", "0"),
		harness.WithHomeFile(".vix/jobs/"+trackerJobID+"/job.json", trackerJobSpec()),
		harness.WithWorkdirFile("feed.txt", a+"\n"+b+"\n"),
	)
	h.UI.WaitStable(500 * time.Millisecond)

	trackerPath := h.HomePath(".vix/jobs/" + trackerJobID + "/tracker.tsv")
	readTracker := func() string {
		bs, err := os.ReadFile(trackerPath)
		if err != nil {
			return ""
		}
		return strings.TrimRight(string(bs), "\n")
	}

	fire := func(runNo int) {
		out, err := h.RunCLI("job", "run", trackerJobID)
		if err != nil {
			t.Fatalf("run %d: vix job run failed: %v\n%s", runNo, err, out)
		}
		if !pollUntil(30*time.Second, func() bool { return countJobRuns(h, trackerJobID) >= runNo }) {
			t.Fatalf("run %d did not complete; tracker=%q\n%s", runNo, readTracker(), h.Daemon.LogTail(80))
		}
	}

	// Run 1: seed both opens as todo, claim the first (A: doing, attempts 1),
	// mark it done. Tracker carries the attempt count in the middle column.
	fire(1)
	want1 := "done\t1\t" + a + "\ntodo\t0\t" + b
	if got := readTracker(); got != want1 {
		t.Fatalf("after run 1 tracker =\n%q\nwant\n%q", got, want1)
	}

	// Run 2 — Fix 1: the fetch fails (FETCH_FAILED). select must NOT rewrite the
	// tracker: it stays byte-for-byte identical, so no item is re-investigated.
	if err := h.FS.Write("fetch_fail", "1"); err != nil {
		t.Fatal(err)
	}
	fire(2)
	if got := readTracker(); got != want1 {
		t.Fatalf("after a FETCH_FAILED run the tracker was modified:\ngot  %q\nwant %q (unchanged)", got, want1)
	}
	if err := os.Remove(h.FS.Path("fetch_fail")); err != nil {
		t.Fatal(err)
	}

	// From here, mark_done is suppressed (skip_done marker) to simulate runs that
	// die before mark_done — leaving the claimed item stuck in "doing".
	if err := h.FS.Write("skip_done", "1"); err != nil {
		t.Fatal(err)
	}

	// Run 3: claim B (todo -> doing, attempts 1); mark_done skipped -> B stuck.
	fire(3)
	want3 := "done\t1\t" + a + "\ndoing\t1\t" + b
	if got := readTracker(); got != want3 {
		t.Fatalf("after run 3 tracker =\n%q\nwant\n%q", got, want3)
	}

	// Run 4 — Fix 2 (retry): the stale "doing" B (attempts 1) is re-armed to
	// todo and re-claimed (attempts 2). It is NOT abandoned yet.
	fire(4)
	want4 := "done\t1\t" + a + "\ndoing\t2\t" + b
	if got := readTracker(); got != want4 {
		t.Fatalf("after run 4 tracker =\n%q\nwant\n%q", got, want4)
	}

	// Run 5 — Fix 2 (bound): B has now used 2 attempts, so it is abandoned
	// (done) instead of retried again — no infinite loop. Nothing left to claim.
	fire(5)
	want5 := "done\t1\t" + a + "\ndone\t2\t" + b
	if got := readTracker(); got != want5 {
		t.Fatalf("after run 5 tracker =\n%q\nwant\n%q", got, want5)
	}
}
